backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
